name: Deploy on Scaleway

on:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Deploy on the machine
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          passphrase: ${{ secrets.SERVER_PW }}
          privateKey: ${{ secrets.SERVER_SSH }}
          command: ./deploy.sh

