name: Deploy on Scaleway

on:
  push:
    branches:
      - 'master'

jobs:
  connect-machine:
    runs-on: ubuntu-18.04
    steps:
      - name: Connect to the machine
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          passphrase: ${{ secrets.SERVER_PW }}
          privateKey: ${{ secrets.SERVER_SSH }}
          script: |
            whoami
            ls -al

